config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/user_information/:id', to: 'pages#user_profile', as: "profile"
  patch '/user_information/:id', to: 'pages#update', as: "profile_update"
  resources :bookings, only: :index

  resources :art_services do
    resources :bookings, only: [:new, :create, :update, :destroy]
    resources :reviews, only: [:new, :create, :destroy]
  end

  patch 'bookings/:id/update_status', to: 'bookings#update_status', as: "update_status"



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/art_service.rb
class ArtService < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  belongs_to :user
  has_many :bookings, :dependent => :delete_all
  has_many :reviews, :dependent => :delete_all

  has_many_attached :photos
  validates :title, :description, :price, :address, :category, presence: true

include PgSearch::Model
  pg_search_scope :search_by_title_and_category, against: [:title, :category],
    using: {
    tsearch: { prefix: true }
    }
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :art_service
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :art_service

  validates :comment, :rating, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :photo
  has_many :art_services
  has_many :bookings
  has_many :bookings_as_booked, through: :art_services, source: :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit
  before_action :configure_permitted_parameters, if: :devise_controller?

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :about])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :about])

    # For app/views/art_services/new.html.erb user_id
    devise_parameter_sanitizer.permit(:sign_up, keys: [:id])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/art_services_controller.rb
class ArtServicesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show, :home, :index]
  before_action :set_art_service, only: [:show, :edit, :update, :destroy]

  def index
    # @art_services = ArtService.all
    @art_services = policy_scope(ArtService).order(created_at: :desc)

    if params[:query].present?
      @art_services = ArtService.search_by_title_and_category(params[:query])
    else
      @art_services = policy_scope(ArtService).order(created_at: :desc)
    end
  end

  def show
    @markers = [{
        lat: @art_service.latitude,
        lng: @art_service.longitude
      }]

    @average = average_rating(@art_service)
    @booking = Booking.new
  end

  def new
    @art_service = ArtService.new
    authorize @art_service
  end

  def edit
  end

  def update
    @art_service.update(art_services_params)
    redirect_to art_service_path(@art_service)
  end

  def destroy
    @art_service.destroy
    redirect_to art_services_path
  end

  def create
    @art_services = ArtService.new(art_services_params)
    @art_services.user = current_user
    authorize @art_services
    if @art_services.save
      redirect_to art_service_path(@art_services)
    else
      render :new
    end
  end

  private

  def art_services_params
    params.require(:art_service).permit(:title, :description, :price, :address, :category, photos: [])
  end

  def set_art_service
    @art_service = ArtService.find(params[:id])
    authorize @art_service
  end

  def average_rating(art_service)
    if art_service.reviews.blank?
      return 0
    else
      all = []
      art_service.reviews.each do |review|
        all << review.rating
      end
      sum = all.inject(0, :+)
      average = sum / art_service.reviews.length
      return average
    end
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show, :home, :index]

  def home
  end

  def user_profile
    @user = User.find(params[:id])
  end

  def index
    policy_scope(Booking)
  end

  def new
    @booking = Booking.new
    @art_service = ArtService.find(params[:art_service_id])
    authorize @booking
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    art_service = ArtService.find(params[:art_service_id])
    @booking.art_service = art_service
    @booking.status = "pending"
    authorize @booking
    if @booking.save!
      redirect_to bookings_path
    else
      render :new
    end
  end

  def update
    @art_service = ArtService.find(params[:art_service_id])
    @art_service.update(art_service_params)
    redirect_to art_service_path(@art_service)
  end

  def destroy
    @art_service = ArtService.find(params[:art_service_id])
    @art_service.destroy(art_service_params)
    redirect_to art_service_path(@art_service)
  end

  def update_status
    @booking = Booking.find(params[:id])
    authorize @booking
    if params[:status] == "cancelled"
      @booking.status = "cancelled"
      @booking.save
    else
      @booking.status = 'confirmed'
      @booking.save
    end
    redirect_to bookings_path
  end

  private


  def booking_params
    params.require(:booking).permit(:start_time, :end_time, :status)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  before_action :set_user, only: [:edit, :update]

  def home
  end

  def edit
  end

  def update
    @user.update(user_params)
    redirect_to bookings_path
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:about, :photo)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  skip_after_action :verify_authorized
  before_action :set_art_service, only: [:new, :create, :destroy]

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.user = current_user
    @review.art_service = @art_service

    if @review.save
      redirect_to art_service_path(@art_service)
    else
      render :new
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to art_service_path(@review.art_service.id)
  end

  private

  def review_params
    params.require(:review).permit(:rating, :comment)
  end

  def set_art_service
    @art_service = ArtService.find(params[:art_service_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/art_services/edit.html.erb
<div id="card">
  <div class="container py-5" style="max-width: 600px; padding-top: 4em;">
    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1555656220-46e30749d330?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1770&q=80)">
      <h3><strong>Edit your art service</strong></h3>
    </div>
    <div class="list py-3">
      <%= simple_form_for @art_service do |a| %>
      <div class="row">
        <div class="col-sm">
          <%= a.input :category %>
        </div>
        <div class="col-sm">
          <%= a.input :price %>
        </div>
      </div>
          <%= a.input :title %>
          <%= a.input :description %>
          <%= a.input :address %>
          <%= a.input :photos, as: :file, input_html: { multiple: true } %>
          <%= a.hidden_field :users_id, value: current_user.id %>
          <%= a.submit "Save & update", class: 'btn btn-dark float-left' %>
        <% end %>
    </div>
    <%= link_to "Delete",
        art_service_path(@art_service),
        method: :delete,
        data: { confirm: "Are you sure?" },
        class: 'float-right' %>
  </div>
</div>

app/views/art_services/index.html.erb
<div class="art-services-index">
  <div class="general-container mt-3">
    <div class="row">
      <div class="col-12 index_title">
        <h1>🎈✨Our Art Services✨🎈</h1>
      </div>
    </div>

  <div class="row">
    <div class="col index_text">
      <% if @query %>
        <p>You searched for <strong><%= @query %></strong>. We found <%= @art_services.count %> art services out of <%= ArtService.count %> on our website.</p>
      <% else %>
        <p> Browse through our art services!
        <br> Available art services at the moment: <%= ArtService.count%></p>
      <% end %>
     <%# <%= link_to "Back to homepage", root_path, class: 'btn btn-primary' %>
    </div>
  </div>



<div class="index_grid">
  <% @art_services.each do |art_service| %>
   <%= link_to art_service_path(art_service), class: "art-service-link" do %>
      <div class="art_service-card">
        <% if art_service.photos.attached?%>
          <div class="art_service-card-image" style="background-image:linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path art_service.photos.first.key%>')"></div>
        <% else %>
          <div class="art_service-card-image" style="background-image:linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= image_path("default-art-service.jpg")%>')" ></div>

        <% end %>
        <div class="art_service-card-content">
          <div class="card-content-top">
            <h4><%= art_service.title %></h4>
            <div class="d-flex art_service_price">
              <i class="material-icons mr-2">€</i> <%= art_service.price %>
            </div>
          </div>
          <p><%= art_service.address %></p>

          <div></div>

        </div>

      </div>
    <% end %>
  <% end %>
</div>

app/views/art_services/new.html.erb
<div id="card">
  <div class="container py-5" style="max-width: 600px; padding-top: 4em;">
    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1555656220-46e30749d330?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1770&q=80)">
      <h3><strong>Create your art service</strong></h3>
    </div>
    <div class="list py-3">
      <%= simple_form_for @art_service do |a| %>
      <div class="row">
        <div class="col-sm">
          <%= a.input :category %>
        </div>
        <div class="col-sm">
          <%= a.input :price %>
        </div>
      </div>
          <%= a.input :title %>
          <%= a.input :description %>
          <%= a.input :address %>
          <%= a.input :photos, as: :file, input_html: { multiple: true } %>
          <%= a.hidden_field current_user.id, :value => current_user.id %>
          <%= a.submit "Save & upload", class: 'btn btn-dark float-left' %>
          <%= link_to "Back", bookings_path, class: 'float-right mt-3' %>
        <% end %>
    </div>
  </div>
</div>

app/views/art_services/show.html.erb
<div class="container">

  <div id="back">
    <i class="fas fa-long-arrow-alt-left"></i><%= link_to "  Back to all art services", art_services_path %>
  </div>

  <h3><%= @art_service.title.upcase %></h3>
  <ul class="service-show-top-info">
    <li>
      <div class="li-item">
        <i class="fa fa-star" aria-hidden="true"></i><p><strong><%= @average.to_i %></strong> (<%= @art_service.reviews.length %>)</p>
      </div>
    </li>
    <li>
      <div class="li-item">
        <i class="fa fa-archive" aria-hidden="true"></i><p> <%= @art_service.category.downcase%></p>
      </div>
    </li>
    <li>
      <div class="li-item">
        <i class="fa fa-user" aria-hidden="true"></i>
        <p>Hosted by <strong><%= @art_service.user.first_name %></strong></p>
      </div>
    </li>
  </ul>

  <% if @art_service.photos.attached? %>
    <div class="gallery-box">
      <div class="service-gallery">
        <% @art_service.photos.each do |photo| %>
          <%# <div class="gallery-item" style="background-image: url('<%= cl_image_path photo.key%>
          <div class="gallery-item">
            <%= cl_image_tag photo.key, class: 'gallery-image'%>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>

  <div class="info">

    <div class="info-item col-8">
      <h4>Description</h4>
      <div class="description">
        <p><%= @art_service.description %></p>
      </div>
    </div>

    <div class="info-item col-4 booking-box">
      <% if current_user != nil %>

        <% if current_user.id == @art_service.user.id %>
          <%= link_to 'Edit', edit_art_service_path(@art_service), class: 'btn btn-dark'%>
          <%= link_to "Delete #{@art_service.title}", art_service_path(@art_service), method: :delete, data: { confirm: "Are your sure?"}, class: 'btn btn-danger' %>
        <% else %>
          <div class="booking-form">
            <%= simple_form_for [ @art_service, @booking ] do |a| %>
              <div class="input-box">
                <div class="input-field">
                  <%= a.input :start_time, as: :date, label: "From:"%>
                </div>
                <div class="input-field">
                  <%= a.input :end_time, as: :date, label: "Until:" %>
                </div>
              </div>
              <%= a.hidden_field current_user.id, :value => 2 %> <!-- current_user.id -->
              <p>Total cost: <%= @art_service.price %>€</p>
              <%= a.button :submit, class: 'btn btn-dark float-right' %>
            <% end %>
          </div>

        <% end %>

      <%else%>
        <%= link_to "Log in to book this service", new_user_session_path, class: 'btn btn-success' %>
      <% end %>
    </div>

  </div>



  <h4>Location</h4>
  <div id="map"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>

  <div class="about">
    <h4>About <%= @art_service.user.first_name %></h4>
    <p><%= @art_service.user.about %></p>
    <div class="about-box">
      <a href="#" class="btn btn-dark">Contact artist</a>
    </div>
  </div>

  <div class="row justify-content-center">
    <%= link_to "Write a Review", new_art_service_review_path(@art_service), class: "btn btn-dark" %>
    <ul id="list-group">
      <% @art_service.reviews.each do |review| %>
        <li id="list-group-item">
          <div class="card-review">
            <div class="item">

              <div class="stars">
                <% review.rating.times do %>
                  <i class="fa fa-star" aria-hidden="true"></i>
                <% end %>
                <p>by <strong><%= review.user.first_name %></strong></p>
              </div>

              <div class="delete-button">
                <% if current_user != nil %>
                  <% if current_user.id == review.user.id || current_user.id == @art_service.user.id %>
                    <%= link_to "Delete this review", art_service_review_path( @art_service, review.id ), method: :delete, class: 'btn btn-danger' %>
                  <% end %>
                <% end %>
              </div>

            </div>

            <p><%= review.comment %></p>
          </div>
        </li>
      <% end %>
    </ul>

  </div>

</div>

app/views/bookings/index.html.erb
<div class="container py-5" style="max-width: 800px; padding-top: 4em;">
  <h1><strong>Hi <%= current_user.first_name %>👋</strong></h1>

  <div>
    <p>Make sure to add some information about yourself and add a pretty picture to your profile.😊</p>
  </div>

  <div class="list py-3">
    <%= simple_form_for current_user, url: profile_path(current_user) do |a| %>
      <%= a.input :about %>
      <%= a.input :photo, as: :file %>
      <%= a.submit "Save & Upload", class: 'btn btn-dark float-left' %>
      <% end %>
  </div>
  <br>
  <div class="abc my-5">
    <h3 class="text-center"><strong>My art services 🎨</strong></h3>
    <%= link_to "+ Create", new_art_service_path %>
    <div class="cards_all d-flex justify-content-center mt-3">
      <% current_user.art_services.each do |art_service| %>
        <div class="card m-2" style="width: 16rem;">
          <div class="card-body">
            <h5 class="card-title"><%= art_service.title %></h5>
            <p class="card-text">Price: <em><%= art_service.price %>€</p></em>
            <%= link_to 'Edit', edit_art_service_path(art_service) %>
            <%= link_to 'Show', art_service_path(art_service), class: 'float-right'%>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>


<div class="container" style="max-width: 800px; padding-top: 4em;">
  <div class="row">

      <div class="col-6">
        <div class="title">
          <strong><h4 class="text-center mb-3">Awesome, people can't <br>wait to see you 🎊</h4></strong>
        </div>

        <% current_user.bookings_as_booked.each do |booking| %>
          <div class="card m-3">
            <div class="card-body">
              <div class="card-text">
                <p><strong>Request by </strong><em><%= booking.user.first_name %></em> for <em><%= booking.art_service.title %></em></p>
                <p><strong>When:</strong> <%= booking.start_time.strftime("%A, %b %e %Y") %></p>
                <p><strong>Where:</strong> <%= booking.art_service.address %></p>
                <p><strong>Revenue: </strong>€<%= booking.art_service.price %></p>
                  <% if booking.status == "confirmed" %>
                    <span><strong>Status: </strong> <span style="color: green"><%= booking.status %></span></span>
                  <% elsif booking.status == "pending" %>
                    <span><strong>Status: </strong></span><span style="color: blue"><%= booking.status %></span>
                    <div class="text-right">
                      <%= link_to "Cancel",update_status_path(booking, status: 'cancelled'), method: 'patch', remote: true, class: 'card-link' %>
                      <%= link_to "Accept", update_status_path(booking, status: 'accepted'), method: 'patch', remote: true, class: "btn btn-flat" %>
                    </div>
                  <% else %>
                    <span><strong>Status: </strong></span><span style="color: red"><%= booking.status %></span>
                  <% end %>
              </div>
            </div>
          </div>
        <% end %>
      </div>


      <div class="col-6">
      <div class="title">
        <strong><h4 class="text-center mb-3">Be ready for your upcoming shows soon 💃</h4></strong>
      </div>
      <% current_user.bookings.each do |booking| %>
        <div class="card m-3">
          <div class="card-body">
            <div class="card-text">
              <p><strong>Request by </strong><em>me</em> for <em><%= booking.art_service.title %></em></p>
              <p><strong>When:</strong> <%= booking.start_time.strftime("%A, %b %e %Y") %></p>
              <p><strong>Where:</strong> <%= booking.art_service.address %></p>
              <p><strong>Revenue: </strong>€<%= booking.art_service.price %></p>
                <% if booking.status == "confirmed" %>
                  <span><strong>Status: </strong> <span style="color: green"><%= booking.status %></span></span>
                <% elsif booking.status == "pending" %>
                  <span><strong>Status: </strong></span><span style="color: blue"><%= booking.status %></span>
                <% else %>
                  <span><strong>Status: </strong></span><span style="color: red"><%= booking.status %></span>
                <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>

  </div>
</div>

app/views/bookings/new.html.erb
<div class="container py-5" style="max-width: 600px; padding-top: 4em;">
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1555656220-46e30749d330?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1770&q=80)">
    <h3><strong>Book an art service now.</strong></h3>
  </div>

  <div class="list py-3">
    <%= simple_form_for [ @art_service, @booking ] do |a| %>
    <div class="row">
      <div class="col-md">
        <%= a.input :start_time, as: :date, label: "From:"%>
      </div>
      <div class="col-sm">
        <%= a.input :end_time, as: :date, label: "Until:" %>
      </div>
    </div>
        <%= a.hidden_field current_user.id, :value => 2 %> <!-- current_user.id -->
        <%= a.button :submit, class: 'btn btn-dark float-right' %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blanchett</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <div class="page-sections">
      <div class="navbar-section">
        <%# Navbar from Le Wagon's UI kit.%>
        <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
          <a class="navbar-brand" href="/">
            <img src=""/>blanchett <%#logo%>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <% if user_signed_in? %>
                <li class="nav-item active">
                  <%= link_to "Explore all", art_services_path, class: "nav-link" %>
                </li>
                <li class="nav-item dropdown">
                  <% if current_user.photo.attached? %>
                    <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
                  <% else %>
                    <%= image_tag "https://images.pexels.com/photos/1983037/pexels-photo-1983037.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
                  <% end %>
                  <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                    <%= link_to "My profile", bookings_path, class: "dropdown-item" %>
                    <%= link_to "Create new art service", new_art_service_path, class: "dropdown-item" %>
                    <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
                  </div>
                </li>
              <% else %>
                <li class="nav-item">
                  <%= link_to "Login", new_user_session_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                  <%= link_to "Become an artist", new_user_registration_path, class: "nav-link" %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
        <div class="notification">
          <span class="notice"><%= notice %></span>
          <span class="alert"><%= alert %></span>
        </div>
      </div>
      <div class="content-section"><%= yield %></div>
      <div class="footer-section">
        <%# Page's Footer  %>
        <div class="footer">
          <div class="footer-links">
            <a href="#"><i class="fab fa-instagram"></i></a>
            <a href="#"><i class="fab fa-facebook"></i></a>
            <a href="#"><i class="fab fa-twitter"></i></a>
            <a href="#"><i class="fab fa-linkedin"></i></a>
          </div>
          <div class="footer-copyright">
            This footer is made with <i class="fas fa-heart"></i> at Le Wagon by blanchett team.
          </div>
        </div>
      </div>
    </div>

  </body>
</html>

app/views/pages/home.html.erb
<div id="home">
  <%# Banner & Search Form %>
  <div class="banner">
    <div class="container">

      <div class="search-form-control">
        <%= form_tag art_services_path, method: 'get' do  %>
        <%= params[:query] %>
        <%# <input class="form-control string required" type="text" name="search[query]" placeholder="Search for art services" id="search_query" /> %>
        <%= text_field_tag :query,
            params[:query],
            class: "form-control search-term",
            placeholder: "Search for an art service"
            %>
        <%= submit_tag "Search", class: "btn btn-flat" %>
        <% end %>
      </div>
      <%= link_to "Browse all art services", art_services_path, class: 'btn btn-primary' %>
    </div>
  </div>

  <%# Main container. %>
  <div class="container py-5">
    <%# Explore Nearby Cards %>
    <div class="text-left">
      <h3>Our mission ✨</h3>
      <br>
      <p>blanchett is a global community, welcoming people from every discipline and culture who seeks to connect with others.
        We believe passionately in the power of creativity to change attitudes, lives and, ultimately, the world.
        At blanchett, we're building a clearinghouse of art services from the world's most inspired artists —
        and a community of curious souls to engage with each other, both online and offline around the world,
        all year long.</p>
    </div>



    <%# End of the page box items %>
    <div class="text-left"><h4>Are you an aspiring artist?</h4></div>
      <div class="call-to-action-box">
        <div class="box-item m-3">
          <div class="text-field">
            <p>Don’t waste your talent. Instead show it to the world and earn some extra income. It’s so easy. Sign up and join our community of talents.</p>
          </div>
          <%= link_to "Learn more", new_user_registration_path, class: 'btn btn-flat' %>
        </div>
        <div class="box-item">
          <img src="https://images.unsplash.com/photo-1609189184127-04652523de91?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2070&q=80" alt="artist-painter-painting">
        </div>
      </div>
  </div>

  <%# Page's Footer  %>
</div>

app/views/reviews/new.html.erb
<div class="container">
  <div class="form">
    <%= simple_form_for [ @art_service, @review ] do |f| %>
      <%= f.input :rating, input_html: { min: '0', max: '5' } %>
      <%= f.input :comment %>
      <%= f.submit "Submit review", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>